spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6380
      password:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  security:
    user:
      name: mjauto
      password: 123456
